### PR TITLE
revise payments more

### PR DESCRIPTION
**Pull request by chadwhitacre**
This PR addresses feedback received [in Slack](https://catapultpgh.slack.com/archives/general/p1459187384000107) on #3:

> a few thoughts:
> 1. does this mean that the pay for a day if you come once in a while will no longer be an option? i think encouraging the recurring payment is good, but having a "one time contribution" option would give people more flexibility.
> 2.  the fact that paypal is monthly recurring and gratipay is weekly recurring could be confusing for some.  
> 3. a.  could we add some qualifiers on the fixed and flex desk rates like "suggested rate"?<br>
>    b. could we give some examples of what members pay or add some language describing the idea behind the pay what you want/can philosophy, something like:  "We know that people use the space to varying degrees and have a wide range of budgets, depending on who they work for, whether or not they're paying out of pocket, what other non-monetary ways in which they contribute to the community, etc.  As such, Catapult operates an honor system with recurring electronic payments. If you'd rather just click and pay without doing any math, feel free to select one of our suggested options using PayPal below. If you'd like to choose your own contribution level, name your price on Gratipay."

(Note that this PR includes #4 and #5, so I'll rebase once those are resolved.)

### CODE REVIEW

**Comment by chadwhitacre** [comment]
> does this mean that the pay for a day if you come once in a while will no longer be an option? i think encouraging the recurring payment is good, but having a "one time contribution" option would give people more flexibility.

This PR addresses this with a new "Visit" section:

screen shot 2016-04-27 at 11 17 54 am

**Comment by chadwhitacre** [comment]
> the fact that paypal is monthly recurring and gratipay is weekly recurring could be confusing for some.

I don't know what to do about this. The Gratipay reference on the page does have "_weekly_" next to it. 😕

**Comment by chadwhitacre** [comment]
> could we add some qualifiers on the fixed and flex desk rates like "suggested rate"?

I added "Suggested amounts are:" to both the Visit and Join sections.

screen shot 2016-04-27 at 11 22 18 am

**Comment by chadwhitacre** [comment]
> could we give some examples of what members pay 

I think the suggested amounts address this.

> or add some language describing the idea behind the pay what you want/can philosophy, something like:

I think this fits well under "Perks." It really is something unique about Catapult (and it handily fills the spot vacated by #4 ;).

screen shot 2016-04-27 at 11 29 17 am

**Comment by wearpants** [comment]
+1

**Comment by elliottw** [comment]
rockin'

**Pull request merged**
