### PR TITLE
commented out device lab

### PR DESCRIPTION
**Pull request by iamstev**
removed device lab from site as discussed at meeting

### CODE REVIEW

**Comment by elliottw** [comment]
@iamstev can you fix these conflicts or should i just do what you were trying to do in the main branch?

**Comment by iamstev** [comment]
Probably just easier to do it on the master.

**Comment by chadwhitacre** [comment]
I've made a new PR in #4.

**Comment by iamstev** [comment]
Great! I wouldn't be able to do it until this weekend.

**Pull request closed without merging**
